### ISSUE TITLE
The selected code is forcibly replaced.

### ISSUE THREAD

**Issue by czkoko** [nvms/wingman#34]
hello @nvms 
The experience of wingman v2 is excellent. Thank you for your contribution.

I found a relatively obvious problem: The selected code is automatically replaced with the generated code, and in many cases the generated code is not suitable for directly replacing the original code.

In addition, if the text button below the code is changed to an easy-to-understand icon button, the interface layout should be more beautiful.
<img width="622" alt="2023-12-10 19 13 39" src="https://github.com/nvms/wingman/assets/90698189/33486743-1754-491f-b8a4-a74a12430eb7">

**Comment by nvms** [comment]
Hi @czkoko

You can change the insertion method of a prompt to change or disable this behavior. Most prompts default to "Replace selection", but you can set it to "None" so that nothing happens:

<img width="633" alt="Screenshot 2023-12-10 at 9 15 25 AM" src="https://github.com/nvms/wingman/assets/17074357/bc7efdee-9614-4e95-bec1-68dc8d0ebaa8">

Totally agree about the icons. I'll try and find some good ones today.

**Comment by czkoko** [comment]
So that's it. I think an automatic and manual switching option can be added to control the Insertion method.
If Insertion is set to manual, the application insertion button will appear under the generated code.
After all, the local model will not be as understanding as GPT4, and many cases will generate unexpected code.

**Comment by nvms** [comment]
I can see how that would be useful. Playing around with where to put this. I'm thinking that somewhere out of the way, like below the chat input, makes the most sense.

<img width="743" alt="Screenshot 2023-12-10 at 4 31 03 PM" src="https://github.com/nvms/wingman/assets/17074357/ae4a9e2b-a586-4709-91ec-49dd89d4ca07">

**Comment by nvms** [comment]
Thank you for the idea. This feature is available now in `2.0.27`.
